# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
